import { LegalLayout } from './LegalLayout';

const sections=[{id:'alcance',label:'Alcance y responsable'},{id:'datos',label:'Datos que tratamos'},{id:'finalidades',label:'Para qué los usamos'},{id:'permisos',label:'Permisos del dispositivo'},{id:'compartimos',label:'Con quién compartimos'},{id:'conservacion',label:'Conservación y seguridad'},{id:'derechos',label:'Tus derechos'},{id:'menores',label:'Personas menores'},{id:'cambios',label:'Cambios y contacto'}];

const PrivacyPolicy=()=> <LegalLayout title="Política de privacidad" eyebrow="Tu información, con claridad" intro="Te explicamos qué información usa DogCatiFy para ofrecerte la app, cómo la protegemos y qué decisiones podés tomar sobre tus datos." summary="Usamos los datos necesarios para operar DogCatiFy. No vendemos tus datos personales. Podés solicitar acceso, corrección, actualización o supresión escribiéndonos." sections={sections} current="privacidad" description="Conocé qué datos trata DogCatiFy, para qué los usa y cómo ejercer tus derechos.">
  <section id="alcance"><p className="legal-number">01</p><h2>Alcance y responsable</h2><p>Esta política aplica al sitio web, la aplicación móvil y los servicios de DogCatiFy. DogCatiFy es responsable del tratamiento de los datos personales recolectados directamente a través de la plataforma.</p><p>Para consultas escribí a <a href="mailto:info@dogcatify.com">info@dogcatify.com</a>. Antes del lanzamiento comercial se incorporarán aquí la razón social y el domicilio del responsable.</p></section>
  <section id="datos"><p className="legal-number">02</p><h2>Datos que tratamos</h2><ul><li><strong>Cuenta y contacto:</strong> nombre, correo, teléfono, foto y datos de tu cuenta.</li><li><strong>Mascotas:</strong> perfil, fotos, especie, raza, edad, peso, alergias, vacunas, medicamentos, antecedentes y documentos que cargues.</li><li><strong>Actividad:</strong> reservas, pedidos, recordatorios, favoritos, comunicaciones y transacciones.</li><li><strong>Comunidad:</strong> publicaciones, comentarios, fotos, adopciones y alertas.</li><li><strong>Ubicación:</strong> aproximada o precisa cuando habilites el permiso.</li><li><strong>Datos técnicos:</strong> dispositivo, versión, accesos, errores y seguridad.</li><li><strong>Aliados:</strong> datos comerciales y operativos de perfiles profesionales.</li></ul></section>
  <section id="finalidades"><p className="legal-number">03</p><h2>Para qué usamos la información</h2><p>Para crear y proteger tu cuenta; organizar perfiles e historial; enviar recordatorios; mostrar servicios y contenido; gestionar reservas, pedidos y pagos; facilitar la comunidad; atender soporte; prevenir fraude; mejorar la plataforma y cumplir obligaciones legales.</p><p>El tratamiento se basa, según corresponda, en prestar el servicio solicitado, tu consentimiento, obligaciones legales o intereses legítimos de seguridad y mejora.</p></section>
  <section id="permisos"><p className="legal-number">04</p><h2>Permisos del dispositivo</h2><p>Podemos solicitar ubicación, cámara, fotografías y notificaciones solo para funciones que los requieren. Podés rechazarlos o revocarlos desde tu dispositivo; algunas funciones podrían dejar de estar disponibles.</p></section>
  <section id="compartimos"><p className="legal-number">05</p><h2>Con quién podemos compartir datos</h2><p>No vendemos tus datos. Compartimos solo lo necesario con proveedores tecnológicos y de pagos, con aliados que deban cumplir una reserva o pedido y con autoridades cuando exista obligación legal.</p><p>Cuando un proveedor opera fuera de Uruguay procuramos medidas adecuadas conforme a la normativa. DogCatiFy no necesita almacenar el número completo de tu tarjeta.</p></section>
  <section id="conservacion"><p className="legal-number">06</p><h2>Conservación y seguridad</h2><p>Conservamos datos mientras la cuenta esté activa y por el tiempo necesario para prestar el servicio, resolver reclamos, prevenir abusos y cumplir la ley. Luego los eliminamos o anonimizamos.</p><p>Aplicamos medidas técnicas y organizativas razonables. Ningún sistema es infalible: usá credenciales seguras y avisá ante accesos no autorizados.</p></section>
  <section id="derechos"><p className="legal-number">07</p><h2>Tus derechos</h2><p>Según la Ley N.º 18.331, podés solicitar acceso, actualización, inclusión, rectificación o supresión de tus datos, y retirar consentimientos para el futuro.</p><p>Escribí a <a href="mailto:info@dogcatify.com">info@dogcatify.com</a>. Podemos verificar tu identidad. También podés acudir a la <a href="https://www.gub.uy/unidad-reguladora-control-datos-personales/" target="_blank" rel="noreferrer">URCDP</a>.</p></section>
  <section id="menores"><p className="legal-number">08</p><h2>Personas menores de edad</h2><p>Las cuentas deben ser creadas por personas con capacidad legal. Las personas menores deben usar DogCatiFy con autorización y supervisión de su representante.</p></section>
  <section id="cambios"><p className="legal-number">09</p><h2>Cambios y contacto</h2><p>Si actualizamos esta política, comunicaremos los cambios relevantes por medios razonables y cambiaremos la fecha de esta página.</p><div className="legal-contact"><span>Privacidad y datos personales</span><a href="mailto:info@dogcatify.com">info@dogcatify.com ↗</a><a href="mailto:soporte@dogcatify.com">soporte@dogcatify.com</a></div></section>
</LegalLayout>;
export default PrivacyPolicy;
