import { LegalLayout } from './LegalLayout';

const sections=[{id:'aceptacion',label:'Aceptación y cuenta'},{id:'plataforma',label:'Qué ofrece DogCatiFy'},{id:'terceros',label:'Servicios de terceros'},{id:'contenido',label:'Contenido y comunidad'},{id:'compras',label:'Reservas, compras y pagos'},{id:'uso',label:'Uso permitido'},{id:'propiedad',label:'Propiedad intelectual'},{id:'disponibilidad',label:'Disponibilidad y responsabilidad'},{id:'cierre',label:'Suspensión y cierre'},{id:'ley',label:'Cambios, ley y contacto'}];

const TermsOfService=()=> <LegalLayout title="Términos de uso" eyebrow="Reglas simples, vínculos claros" intro="Estas condiciones explican cómo podés usar DogCatiFy, qué podés esperar de la plataforma y qué corresponde a los profesionales y comercios aliados." summary="DogCatiFy organiza el cuidado y conecta personas con aliados. No reemplaza la atención veterinaria. Tus derechos obligatorios como consumidor siempre se mantienen." sections={sections} current="terminos" description="Condiciones de uso de DogCatiFy para funciones, reservas, compras, comunidad y servicios aliados.">
  <section id="aceptacion"><p className="legal-number">01</p><h2>Aceptación y cuenta</h2><p>Al crear una cuenta o utilizar DogCatiFy aceptás estos términos y la Política de privacidad. Debés brindar información verdadera, proteger tus credenciales y avisarnos ante usos no autorizados. Las personas menores requieren autorización y supervisión de su representante.</p></section>
  <section id="plataforma"><p className="legal-number">02</p><h2>Qué ofrece DogCatiFy</h2><p>La plataforma permite gestionar perfiles e historial de mascotas, recordatorios, servicios, lugares pet-friendly, pedidos, comunidad, adopciones, alertas y asistencia digital. Las funciones pueden variar según versión, país y disponibilidad.</p><p>La información y los recordatorios son herramientas de organización y no sustituyen el criterio profesional.</p></section>
  <section id="terceros"><p className="legal-number">03</p><h2>Profesionales, comercios y terceros</h2><p>Los aliados son terceros independientes salvo indicación expresa. DogCatiFy facilita la conexión y las operaciones; cada aliado responde por su descripción, disponibilidad, calidad, seguridad, precio y ejecución.</p><p>DogCatiFy no brinda diagnóstico ni atención veterinaria. Ante una emergencia, contactá directamente a un profesional o servicio de urgencia.</p></section>
  <section id="contenido"><p className="legal-number">04</p><h2>Contenido y comunidad</h2><p>Conservás la titularidad de lo que publicás y otorgás una licencia limitada a alojarlo y mostrarlo para operar la plataforma. Solo podés publicar contenido propio o autorizado.</p><p>No se admite contenido ilegal, engañoso, discriminatorio, que vulnere derechos, promueva maltrato animal, fraude o acoso. Podemos moderarlo o retirarlo.</p></section>
  <section id="compras"><p className="legal-number">05</p><h2>Reservas, compras, pagos y cancelaciones</h2><p>Antes de confirmar una operación se informarán el proveedor, características esenciales, precio, cargos y condiciones aplicables. La confirmación debe ser expresa y los pagos pueden ser procesados por terceros.</p><p>Cancelaciones y reembolsos dependen de la operación, la política informada y la ley. Estos términos no limitan derechos obligatorios del consumidor, incluido el arrepentimiento en contrataciones a distancia cuando corresponda.</p></section>
  <section id="uso"><p className="legal-number">06</p><h2>Uso permitido</h2><p>No podés infringir leyes o derechos; suplantar identidades; acceder sin autorización; afectar la seguridad; extraer datos automáticamente sin permiso; distribuir software malicioso; manipular reseñas u operaciones; ni dañar a personas, animales o la comunidad.</p></section>
  <section id="propiedad"><p className="legal-number">07</p><h2>Propiedad intelectual</h2><p>La marca, diseño, software y contenido propio de DogCatiFy están protegidos. Recibís un permiso personal, limitado, revocable y no transferible para usar la plataforma, no derechos sobre su marca o software.</p></section>
  <section id="disponibilidad"><p className="legal-number">08</p><h2>Disponibilidad y responsabilidad</h2><p>Puede haber mantenimiento, errores o cambios. En la medida permitida por ley, no respondemos por terceros independientes, uso indebido o eventos fuera de nuestro control razonable.</p><p>Nada limita responsabilidades legalmente inderogables ni derechos irrenunciables del consumidor.</p></section>
  <section id="cierre"><p className="legal-number">09</p><h2>Suspensión y cierre de cuenta</h2><p>Podés solicitar el cierre. Podemos limitar el acceso ante incumplimientos, fraude, riesgo, requerimiento legal o discontinuación. El cierre no extingue obligaciones pendientes ni conservación legal de datos.</p></section>
  <section id="ley"><p className="legal-number">10</p><h2>Cambios, ley aplicable y contacto</h2><p>Los cambios relevantes se comunicarán por medios razonables. Estos términos se rigen por las leyes de Uruguay, sin perjuicio de las normas y jurisdicciones imperativas de protección al consumidor.</p><div className="legal-contact"><span>Consultas legales y soporte</span><a href="mailto:legal@dogcatify.com">legal@dogcatify.com ↗</a><a href="mailto:soporte@dogcatify.com">soporte@dogcatify.com</a></div></section>
</LegalLayout>;
export default TermsOfService;
